### ISSUE TITLE
TA for BS 1.19+

### ISSUE THREAD

**Issue by ByteAlex** [MatrikMoon/TournamentAssistant#34]
Hi.

We were testing TA for a tournament planned in about 2 weeks with version 1.19, though it seems that version broke the latest TA version.

The following error is what I am observing:
`[INFO @ 16:20:05 | _] System.MissingMethodException: void PlayerSpecificSettings..ctor(bool,single,bool,single,bool,bool,bool,bool,bool,single,single,bool,bool,EnvironmentEffectsFilterPreset,EnvironmentEffectsFilterPreset)
[INFO @ 16:20:05 | _]   at TournamentAssistantShared.Sockets.Client.ReadCallback (System.IAsyncResult ar) [0x000a8] in <21662bde7ba94ae082387bf67483f192>:0 `

In game it's visible by trying to connect to a TA server, which will hang in "connecting" screen, even though the client appears on the TA server almost immediately.
A game cannot be started.

I hope you can have a look at it. 
Thank you & Best
Alex

**Comment by MatrikMoon** [comment]
Howdy! Thanks for bringing this to my attention! I've been out of town since the 15th so I haven't had the chance to look for myself.

The good news is that these sorts of updates are usually easy-peasy-lemon-squeezy from my side! Reach out to me on discord if you'd like to have a more real-time chat on the matter.

To anyone else reading this, expect it to be closed and fixed within a reasonable amount of time.

**Comment by ByteAlex** [comment]
Thanks for answering that quickly! If you could please send me your discord tag, so I know to whom I may talk, that would be super cool!

**Comment by MatrikMoon** [comment]
Mmm it's `moon#0002`, coulda sworn it was listed on the Readme. I'll have to check.
